version: "3"
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - auth
    networks:
      - spring-cloud-network

  auth:
    build: ./auth
    expose:
      - 8081
    depends_on:
      - auth-db
    networks:
      - spring-cloud-network

  auth-db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_ROOT_PASSWORD=mysqlrootpw
      - MYSQL_PORT=3306
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
