version: "3"
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - auth
    networks:
      - spring-cloud-network

  auth:
    build: ./auth
    expose:
      - 8081
    depends_on:
      - auth-db
    networks:
      - spring-cloud-network

  auth-db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_ROOT_PASSWORD=mysqlrootpw
      - MYSQL_PORT=3306
    networks:
      - spring-cloud-network

  transaction:
    build: ./transactions
    expose:
      - 8082
    depends_on:
      - transaction-db
    networks:
      - spring-cloud-network

  transaction-db:
    image: mysql:8
    ports:
      - "3308:3306"
    depends_on:
      - rabbitmq
    environment:
      - MYSQL_DATABASE=transaction
      - MYSQL_ROOT_PASSWORD=mysqlrootpw
      - MYSQL_PORT=3306
    networks:
      - spring-cloud-network

  rabbitmq:
    image: rabbitmq:management
    expose:
      - 5672
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
